# -*- coding: utf-8 -*-
"""Algoritmo-de-Auditoria-de-Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dgraL6xCUNlvtRpdrYWhOWRD9wM5Z3f
"""

LIMITE_SEGURANCA = 8000.00

# Entrada

ven1 = float(input("Venda1: "))
ven2 = float(input("Venda2: "))
ven3 = float(input("Venda3: "))

def analisar_vendas(ven1, ven2, ven3):

    media = (ven1 + ven2 + ven3) / 3

    print("Media", media)

    global LIMITE_SEGURANCA

    if media > LIMITE_SEGURANCA:

        print("SISTEMA EM QUARENTENA")

    for v in (ven1, ven2, ven3):

        if v > media * 5:

            print("REVISÃO MANUAL!")

            break

    print(f"Tipo Venda1{type(ven1)}")

    print(f"Tipo Venda1{type(ven2)}")

    print(f"Tipo Venda1{type(ven3)}")

    print(f"Tipo Limite seguranca{type(LIMITE_SEGURANCA)}")

    print(f"Tipo media{type(media)}")



analisar_vendas(ven1, ven2, ven3)