# -*- coding: utf-8 -*-
"""biblioteca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAHF1Fe4iS7ThUYhaMO2Pz2tWwNPX9lB
"""

biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}

for chave, valor in biblioteca_musical.items():

 for linha in valor:

  for nome, tupla in linha.items():      # "Alegre" → ([440,480],[520,560])



       tupla_invertida = tupla[::-1]      # inverte a ordem da tupla



       linha.update({nome: tupla_invertida})  # substitui o valor no dicionário



print(biblioteca_musical)



desafio 3



info = ("Minha Playlist", 3, "Imagens")



imagens = {

  "categoria1": ["🍇", "🌛", "❤︎"]

}



processadas = []



for categoria in imagens.keys():

  print(f"Categoria: {categoria}")



  for imagem in imagens[categoria]:

    print(f"Processando: {imagem}")



    for letra in imagem:

      print(letra, end="")

    print()



    processadas.insert(0, imagem)



print(f"\nImagens processadas: {processadas}")