# -*- coding: utf-8 -*-
"""emoji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-_OmqwmtD74Cv6EVHc0s-zYC3lPrVRL
"""

import matplotlib.pyplot as plt



emoji_data = {

  "nome": "Smile",

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0

    [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)], # Linha 1 (Olhos)

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2

    [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)], # Linha 3 (Boca)

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)] # Linha 4

  ]

}



pixels_modificados = []

for chave, lote in emoji_data.items():

  if chave == "grade":

    for linha in lote:

      for pixel in linha:



        if pixel == (255, 255, 0): # Se amarelo, aplica sombra

          novo_pixel = (pixel[0] // 2,

                 pixel[1] // 2,

                 pixel[2] // 2)

        else:

          novo_pixel = pixel   # Preto permanece igual



        pixels_modificados.append(novo_pixel)



print(pixels_modificados)

plt.imshow(emoji_data["grade"])

plt.show()