# -*- coding: utf-8 -*-
"""Sistema-de-auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFsd79ufnXCUbrhpAKJNlgdWgH8gpjDy

# Sistema de Auditoria de Recursos Corporativos
Laura Maciel Ferreira dos Santos
"""

from functools import wraps
import time

dados_empresariais = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 20000,
                "Seguranca": 10000
            },
            "Desenvolvimento": {
                "Frontend": 7000,
                "Backend": 10000,
                "Devops": 4000
            }
        },
        "RH": {
            "Recrutamento": 5000,
            "Treinamento": 7000,
            "Cultura": {
                "Eventos": 3000,
                "Brindes": 1200
            }
        },
        "Financeiro": 20000
    }
}

def auditor(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("\n" + "=" * 50)
        print(f"Início da auditoria para '{func.__name__}'")
        print("=" * 50)
        print(f"Departamentos ignorados ❌: {args[1:]}")
        print(f"Parâmetros de conversão: {kwargs}")

        start = time.time()
        resultado = func(*args, **kwargs)
        fim = time.time()

        print(f"Tempo de execução ⏳: {fim - start:.4f}s")
        print(f"Fim da auditoria para '{func.__name__}'")
        print("-" * 50)

        return resultado
    return wrapper

def _recursao(dados, departamentos_ignorados):
    total = 0
    if isinstance(dados, dict):
        for chave, valor in dados.items():
            if chave in departamentos_ignorados:
                continue
            total += _recursao(valor, departamentos_ignorados)
    else:
        total += dados
    return total

@auditor
def calcular_orcamento(dados, *ignorados, **kwargs):
    total = _recursao(dados, ignorados)
    taxa = kwargs.get('taxa_cambio', 5.20)
    return total * taxa

orcamento1 = calcular_orcamento(dados_empresariais, "RH", "Infraestrutura", moeda="BRL", taxa_cambio=5.20)
print(f"Total: R$ {orcamento1:.2f}")

orcamento2 = calcular_orcamento(dados_empresariais, "TI", "Financeiro")
print(f"Total: R$ {orcamento2:.2f}")

orcamento3 = calcular_orcamento(dados_empresariais)
print(f"Total geral da empresa (em BRL): R$ {orcamento3:.2f}")