# -*- coding: utf-8 -*-
"""evacuacaofisica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYaNPVL8ToyL5bultAmJScflhn7w0jqd
"""

def simular_evacuacao():

  rota = ["Quarto", "Corredor", "Escada", "Sala", "Saída principal"]



  estudos = ["Caminho livre", "Porta fechada", "Escada com curva", "Rua"]



  posicao_atual = 0

  inventario = []

  energia = 10

  evacuado = False

  print(f" Início da evacuação: saindo do(a) {rota[posicao_atual]} ---")



  while energia > 0 and not evacuado:

    local_atual = rota[posicao_atual]

    obstaculo = estudos[posicao_atual]



    print(f"\n agente está no(a): {local_atual.lower()}")

    print(f" status: {obstaculo.lower()} energia {energia}")



    if obstaculo == "Caminho livre":

      print(" Descendo escada com cuidado.")

      posicao_atual += 1



    elif obstaculo == "Escada com curva":

      print("O agente encontrou uma escada com cuidado.")

      inventario.append("Descendo escada")

      posicao_atual += 1



    elif obstaculo == "Porta fechada":

      if "chave" in inventario:

        print("Usando a chave para abrir a porta e avançando!")

        posicao_atual += 1

      else:

        print("Porta fechada! Voltando para procurar a chave...")

        inventario.append("chave")

        posicao_atual -= 1



    elif obstaculo == "Rua":

      evacuado = True

    energia -= 1



    if evacuado:

      print("\n Sucesso! O agente chegou à rua em segurança !!")

    else:

      print("\n  A energia acabou. O agente ficou preso no prédio.")

simular_evacuacao()