# -*- coding: utf-8 -*-
"""iqafisica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uD_QD1udVxb24FjQdB8hI3HlVTl5wQjU
"""

def analisar_dados():

  dados_locais = [

    ["Metrô", 23, 72, 112],

    ["Shopping Anália Franco", 25, 52, 84],

    ["UNICID Tatuapé", 26, 54, 126],

  ]

  print(f"\n{'local':<25} {'classe iqa'}")

  print("─" * 40)

  for local in dados_locais:

    nome, temperatura, umidade, iqa = local

    match iqa:

      case n if n <= 40:

        classe_iqa ="Boa"

      case n if 41 <= n <= 80:

        classe_iqa = "Moderada"

      case n if 81 <= n <= 120:

        classe_iqa = "Ruim"

      case n if 121 <= n <= 200:

        classe_iqa = "Muito Ruim"

      case _:

        classe_iqa = "Perigosa"

    print(f"{nome}: {classe_iqa}")



import math

def pT(T):

  return math.exp(-((T - 22) / 10) ** 2)



def pU(UR):

  return max(0.0, 1 - (abs(UR - 50) / 50) ** 1.5)



def pIQA(IQA):

  return max(0.0, 1 - (IQA / 200) ** 0.8)



def ncu(T, UR, IQA):

  if IQA >= 300: return 0.0

  return round(10 * (0.45 * pT(T) + 0.30 * pU(UR) + 0.25 * pIQA(IQA)), 2)



def classificar(nota):

  if nota >= 8.5: return "Excelente"

  elif nota >= 7.0: return "Bom"

  elif nota >= 5.0: return "Moderado"

  elif nota >= 3.0: return "Ruim"

  else: return "Crítico"



locais = [

  {"nome": "Metrô Vila Matilde", "Temperatura": 23, "Umidade": 72, "IQA": 112},

  {"nome": "Shopping Anália Franco", "Temperatura": 25, "Umidade": 52, "IQA": 84},

  {"nome": "UNICID Tatuapé", "Temperatura": 26, "Umidade": 54, "IQA": 126},

]



print(f"\n{'Local':<25} {'Temp':>6} {'Umid':>6} {'IQA':>6} {'NCU':>6} Classe")

print("─" * 65)



for local in locais:

  nota = ncu(local["Temperatura"], local["Umidade"], local["IQA"])

  classe = classificar(nota)



  print(f"{local['nome']:<25} "

     f"{local['Temperatura']:>5}°C "

     f"{local['Umidade']:>5}% "

     f"{local['IQA']:>6} "

     f"{nota:>6.2f} {classe}")



analisar_dados()